### ISSUE TITLE
Upload to the KDE Store

### ISSUE THREAD

**Issue by NNBnh** [catppuccin/konsole#3]
As the title suggest. This will make installing the theme way more convenient.

**Comment by Esgariot** [comment]
this one (https://store.kde.org/u/catppuccin) looks pretty official to me, could just update readme

**Comment by sgoudham** [comment]
> this one ([store.kde.org/u/catppuccin](https://store.kde.org/u/catppuccin)) looks pretty official to me

I can confirm that this is the official account, I'm a bit busy at the moment but more than happy to review/accept a PR updating the README.
